package model;
// Generated 26.Ağu.2019 09:08:06 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin")
public class Admin implements java.io.Serializable {

	private Integer aid;
	private String aname;
	private String amail;
	private String apass;

	public Admin() {
	}

	public Admin(String aname, String amail, String apass) {
		this.aname = aname;
		this.amail = amail;
		this.apass = apass;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "aid", unique = true, nullable = false)
	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	@Column(name = "aname", nullable = false)
	public String getAname() {
		return this.aname;
	}

	public void setAname(String aname) {
		this.aname = aname;
	}

	@Column(name = "amail", nullable = false)
	public String getAmail() {
		return this.amail;
	}

	public void setAmail(String amail) {
		this.amail = amail;
	}

	@Column(name = "apass", nullable = false, length = 32)
	public String getApass() {
		return this.apass;
	}

	public void setApass(String apass) {
		this.apass = apass;
	}

}
