package model;
// Generated Oct 1, 2019 12:06:46 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "foodtown")
public class Customer implements java.io.Serializable {

	private Integer cstid;
	private String cstname;
	private String cstmail;
	private String cstpassword;
	private int orderid;

	public Customer() {
	}

	public Customer(String cstname, String cstmail, String cstpassword, int orderid) {
		this.cstname = cstname;
		this.cstmail = cstmail;
		this.cstpassword = cstpassword;
		this.orderid = orderid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cstid", unique = true, nullable = false)
	public Integer getCstid() {
		return this.cstid;
	}

	public void setCstid(Integer cstid) {
		this.cstid = cstid;
	}

	@Column(name = "cstname", nullable = false)
	public String getCstname() {
		return this.cstname;
	}

	public void setCstname(String cstname) {
		this.cstname = cstname;
	}

	@Column(name = "cstmail", nullable = false)
	public String getCstmail() {
		return this.cstmail;
	}

	public void setCstmail(String cstmail) {
		this.cstmail = cstmail;
	}

	@Column(name = "cstpassword", nullable = false)
	public String getCstpassword() {
		return this.cstpassword;
	}

	public void setCstpassword(String cstpassword) {
		this.cstpassword = cstpassword;
	}

	@Column(name = "orderid", nullable = false)
	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

}
