package model;
// Generated Oct 1, 2019 12:06:46 AM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Productorder generated by hbm2java
 */
@Entity
@Table(name = "productorder", catalog = "foodtown")
public class Productorder implements java.io.Serializable {

	private Integer oid;
	private String otitle;
	private String odesc;
	private String ophoto;
	private BigDecimal oprice;
	private int oqty;
	private String ostatu;
	private String otime;
	private String odtime;

	public Productorder() {
	}

	public Productorder(String otitle, String odesc, String ophoto, BigDecimal oprice, int oqty, String ostatu,
			String otime, String odtime) {
		this.otitle = otitle;
		this.odesc = odesc;
		this.ophoto = ophoto;
		this.oprice = oprice;
		this.oqty = oqty;
		this.ostatu = ostatu;
		this.otime = otime;
		this.odtime = odtime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "oid", unique = true, nullable = false)
	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	@Column(name = "otitle", nullable = false)
	public String getOtitle() {
		return this.otitle;
	}

	public void setOtitle(String otitle) {
		this.otitle = otitle;
	}

	@Column(name = "odesc", nullable = false)
	public String getOdesc() {
		return this.odesc;
	}

	public void setOdesc(String odesc) {
		this.odesc = odesc;
	}

	@Column(name = "ophoto", nullable = false, length = 500)
	public String getOphoto() {
		return this.ophoto;
	}

	public void setOphoto(String ophoto) {
		this.ophoto = ophoto;
	}

	@Column(name = "oprice", nullable = false, precision = 10)
	public BigDecimal getOprice() {
		return this.oprice;
	}

	public void setOprice(BigDecimal oprice) {
		this.oprice = oprice;
	}

	@Column(name = "oqty", nullable = false)
	public int getOqty() {
		return this.oqty;
	}

	public void setOqty(int oqty) {
		this.oqty = oqty;
	}

	@Column(name = "ostatu", nullable = false)
	public String getOstatu() {
		return this.ostatu;
	}

	public void setOstatu(String ostatu) {
		this.ostatu = ostatu;
	}

	@Column(name = "otime", nullable = false)
	public String getOtime() {
		return this.otime;
	}

	public void setOtime(String otime) {
		this.otime = otime;
	}

	@Column(name = "odtime", nullable = false)
	public String getOdtime() {
		return this.odtime;
	}

	public void setOdtime(String odtime) {
		this.odtime = odtime;
	}

}
